name: Comment on invalid interaction
on:
  workflow_call:

jobs:
  add-comment-on-invalid:
    if: github.event.label.name == 'invalid'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment on invalid
        uses: peter-evans/create-or-update-comment@1.4.5
        with:
          issue-number: ${{ github.event.issue.number}}
          body: |
            A human has marked this issue as invalid, this likely happened because the issue template was not used in the creation of the issue.
