name: Mark stale issues and pull requests

on:
  workflow_call:

permissions:
  issues: write
  pull-requests: write

concurrency:
  group: lock

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v8.0.0
        with:
          close-issue-label: closed-issue-activity
          close-pr-label: closed-pr-activity
          stale-issue-label: no-issue-activity
          stale-issue-message: This issue has been automatically marked as stale because it has not had recent activity. This might be due to missing feedback from OP. It will be closed if no further activity occurs. Thank you for your contributions.
          stale-pr-label: no-pr-activity
          stale-pr-message: This pull request has been automatically marked as stale because it has not had recent activity. This might be due to missing feedback from OP. It will be closed if no further activity occurs. Thank you for your contributions.
          days-before-stale: 30
          days-before-close: 60
          exempt-issue-labels: awaiting-approval,work-in-progress
          exempt-pr-labels: awaiting-approval,work-in-progress
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          operations-per-run: 400

      - name: sleep for ratelimit
        run: sleep 380

  lock:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs:
      - stale

    steps:
      - uses: dessant/lock-threads@v4.0.0
        with:
          issue-inactive-days: "30"
          include-any-issue-labels: no-issue-activity
          issue-comment: This issue is locked due to inactivity
          exclude-any-issue-labels: awaiting-approval,work-in-progress
          pr-inactive-days: "30"
          include-any-pr-labels: no-pr-activity
          pr-comment: This pull request is locked due to inactivity
          exclude-any-pr-labels: awaiting-approval,work-in-progress
