name: Mark stale issues and pull requests

on:
  workflow_call:

permissions:
  issues: write
  pull-requests: write

concurrency:
  group: lock

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v8.0.0
        with:
          close-issue-label: closed-issue-activity
          close-issue-message: This issue is closed due to lack of feedback needed to resolve the issue. If not further action is taken, this issue will be closed.
          close-pr-label: closed-pr-activity
          close-pr-message: This pull request is closed due to lack of feedback needed to merge the pull request. If not further action is taken, this pull request will be closed.
          days-before-close: 60
          days-before-stale: 30
          exempt-issue-labels: awaiting-approval,work-in-progress
          exempt-pr-labels: awaiting-approval,work-in-progress
          stale-issue-label: no-issue-activity
          stale-issue-message: This issue has been automatically marked as stale because it has not had recent activity. This might be due to missing feedback from OP. It will be closed if no further activity occurs. Thank you for your contributions.
          stale-pr-label: no-pr-activity
          stale-pr-message: This pull request has been automatically marked as stale because it has not had recent activity. This might be due to missing feedback from OP. It will be closed if no further activity occurs. Thank you for your contributions.
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          operations-per-run: 400

      - name: sleep for ratelimit
        run: sleep 380

  lock:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs:
      - stale

    steps:
      - uses: dessant/lock-threads@v4.0.0
        with:
          issue-inactive-days: "30"
          include-any-issue-labels: no-issue-activity
          exclude-any-issue-labels: awaiting-approval,work-in-progress
          pr-inactive-days: "30"
          include-any-pr-labels: no-pr-activity
          exclude-any-pr-labels: awaiting-approval,work-in-progress
